name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup env variable
        uses: nookery/env-replace-action@main
        env:
          oss.accessKeyID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          oss.accessKeySecret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag skynesser/go-aliyunoss:latest





